### ISSUE TITLE
PA Review: Notebooks

### ISSUE THREAD

**Issue by milesmcleod** [milesmcleod/purplenote#5]
Link: [Purplenote Heroku](https://purplenote.herokuapp.com)

- [x] Users can create, view, update, and delete notebooks.
- [x] Users can add notes to notebooks.
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Great job! The new notebook functionality modal looks great, kudos for the addition of the confirm modal for deleting notebooks, our users will thank us for not letting them delete their notebooks by miss clicking on the trash icon. Incredible execution of your MVP, the attention to detail is incredible, like not being able to delete your default notebook.

Just a few minor details.
+ Can we setup an Icon for creating new notebooks (_N_ looks a bit off).
+ For the trash notebook, it is displaying a placeholder value of *trashcount*.
+ Can we implement the `esc` functionality when creating/updating notebooks to cancel the action?
+ It looks like sort by is not popping out on the notebook show.

**Comment by milesmcleod** [comment]
Yo. Looks like I've hit all these points. I'm about to push it up to heroku. The only thing I haven't implemented yet is switching out the _N_, which is a placeholder for an icon I haven't built yet. I'm waiting to build out the icons (I have 4 more to make for the tags MVP as well) until I hit this last piece of the tags puzzle, and then I'll update the icons. Otherwise, these updates are in place.

**Comment by AAlfarho** [comment]
Great work!
Final detail I noticed.
+ When trying to edit/delete a notebook, hitting `esc` the modal _semi_ closes but not completely disappears, it only closed after clicking _close_. After hitting `esc` I'm still able to act upon the modal.

**Comment by AAlfarho** [comment]
As for the icons, please submit an issue to keep track of this.

**Comment by milesmcleod** [comment]
Submitted the icons issue. Hitting ESC seems to work on my computer, could this be an issue with the key code I'm binding on?

**Comment by AAlfarho** [comment]
Great job, MVP completed.
