### ISSUE TITLE
PA Review: Tags

### ISSUE THREAD

**Issue by milesmcleod** [milesmcleod/purplenote#6]
Link: [Purplenote Heroku](https://purplenote.herokuapp.com)

- [x] Users can create, view, update, and delete tags.
- [x] Users can assign tags to notes.
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Great job Miles, kudos on the editing transitions for the tag editing.
Quick question, what does the S stands for in the tags?

**Comment by milesmcleod** [comment]
Shortcut! I've added icons to everything now, and I'm pushing to Heroku. All the shortcut icons are dead for now, but as soon as I get the rich text editor implemented, I'm going to add them. Shortcuts behave just like notebooks, except that notebooks, notes, and tags are all shortcuttable. I'm going to use polymorphic associations and a similar slide-out nav to implement it.

**Comment by AAlfarho** [comment]
Great job!
Those icons complement really well the site.
