### ISSUE TITLE
PA Review: Rich-text editing

### ISSUE THREAD

**Issue by milesmcleod** [milesmcleod/purplenote#7]
Link: [Purplenote Heroku](https://purplenote.herokuapp.com)

Users are provided with a rich-text editor with the following features:
- [x] Font
- [x] Font-size
- [x] Font color, weight, italics, underline, strikethrough
- [x] Checkbox, bulleted list, and numbered list
- [x] Text-alignment, indenting, and unindenting
- [x] Note formatting is saved and is present when notes are loaded into the editor
- [x] Toolbar is responsive to screen width and scrolls sideways
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Incredible job!
The new layout for the notes, quill, notebooks feels natural and smooth, kudos in the integration of these components.
This completes the last coding MVP of the project! Continue raising issues to keep track of enhancements and future changes you plan to do on your app.
